name: Auto-Update Packagist

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  update-packagist:
    runs-on: ubuntu-latest

    steps:
      - name: Update Packagist package
        run: |
          curl -sS -XPOST \
            -H "Content-Type: application/json" \
            "https://packagist.org/api/update-package?username=${PACKAGIST_USERNAME}&apiToken=${PACKAGIST_TOKEN}" \
            -d '{"repository":{"url":"https://github.com/lukman-ss/http"}}'
        env:
          PACKAGIST_USERNAME: ${{ secrets.PACKAGIST_USERNAME }}
          PACKAGIST_TOKEN: ${{ secrets.PACKAGIST_TOKEN }}
